import {
  AlignCenter,
  Award,
  Battery,
  CheckCircle,
  Circle,
  Clipboard,
  Clock,
  Cpu,
  CreditCard,
  Disc,
  Droplet,
  Droplets,
  Filter,
  FlaskConical,
  Gauge,
  GitBranch,
  Layers,
  Link,
  Maximize2,
  Monitor,
  MoveVertical,
  RefreshCw,
  RotateCw,
  Settings,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sliders,
  SlidersHorizontal,
  Snowflake,
  Square,
  Star,
  Target,
  Thermometer,
  Trophy,
  Truck,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

// Mapa explícito de ícones referenciados por nome (string) nos dados de
// serviços. Importar apenas os ícones usados permite o tree-shaking do
// lucide-react (antes, `import * as` arrastava a biblioteca inteira ~850 KB).
export const iconMap: Record<string, LucideIcon> = {
  AlignCenter,
  Award,
  Battery,
  CheckCircle,
  Circle,
  Clipboard,
  Clock,
  Cpu,
  CreditCard,
  Disc,
  Droplet,
  Droplets,
  Filter,
  FlaskConical,
  Gauge,
  GitBranch,
  Layers,
  Link,
  Maximize2,
  Monitor,
  MoveVertical,
  RefreshCw,
  RotateCw,
  Settings,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sliders,
  SlidersHorizontal,
  Snowflake,
  Square,
  Star,
  Target,
  Thermometer,
  Trophy,
  Truck,
  Wind,
  Wrench,
  Zap,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] || Circle;
}
